Add: Bidirectional video support
EpicGames/PixelStreamingInfrastructure pull request #251
Opened 2024-08-26 04:43 UTC by Belchy06

## Relevant components:
- [ ] Signalling server
- [ ] Common library
- [X] Frontend library
- [X] Frontend UI library
- [ ] Matchmaker
- [ ] Platform scripts
- [ ] SFU

## Problem statement:
PixelStreaming is currently only able to receive video from the Unreal Engine. WebRTC supports bidirectional video, but this functionality hasn't been added to the frontend... until now.

## Solution
This PR adds support for sending the browser webcam back to the Unreal Engine for processing and display.

## Documentation
Updated all relevant docs.

## Test Plan and Compatibility
Tested the PixelStreaming still works in both UseCamera states.

2024-08-26 04:43 UTC, Belchy06 commented
NOTE: Type names and docs links will need to be updated once confirmed.

2024-08-26 04:52 UTC, lukehb commented on Frontend/library/src/PeerConnectionController/PeerConnectionController.ts
> +            const mediaSendOptions: MediaStreamConstraints = {
Can the else block by moved out into its own function like `setupVideoSender()`

2024-08-26 05:03 UTC, lukehb requested changes
Minor change requesting transceiver setup with camera to be factored out into its own function.

2024-08-28 03:55 UTC, lukehb commented
Prettier is also catching some issues with the code it seems.

2024-08-28 04:14 UTC, mcottontensor commented
Looks like indenting issues. Can probably just use `npm run lint -- --fix`

2024-09-02 23:17 UTC, merged