Fix unhandled error on client from SettingOption.ts
EpicGames/PixelStreamingInfrastructure pull request #299
Opened 2024-10-13 18:35 UTC by richardFocus

## Relevant components:
- [ ] Signalling server
- [ ] Common library
- [ X] Frontend library
- [ ] Frontend UI library
- [ ] Matchmaker
- [ ] Platform scripts
- [ ] SFU

## Problem statement:
I have been having unhandled errors in production and found this update solves the issue we were having originating from SettingOptions.ts:
![settingOptionsError](https://github.com/user-attachments/assets/ab47ca26-3478-4f7b-98d2-6a0ad4cf98f0)

## Solution
The was an issue with the options not being ready in time, I am not sure if this is the best way to solve the bug as it may be better to solve elsewhere in the codebase but this has fixed the issue for us and now I don't get anymore production errors, if someone else knows a better fix then go for it.

##Testing
I have been running this code in productions for weeks now and no more issues that were occurring previously at least every few days.

2024-10-31 04:22 UTC, lukehb requested changes
The change to add some error handling seem okay.

@mcottontensor I think the logging to console should use our logging class instead, right?

2024-10-31 04:24 UTC, lukehb requested changes
Some further changes come to mind making it even safer.

2024-10-31 04:24 UTC, lukehb commented on Frontend/library/src/Config/SettingOption.ts
> +        const valueCodec = value.split(' ')[0];
`value.split(' ')[0]` could itself fail (same with above on line 83) - I would request some defensive programming be done around that too, e.g. check if split results in a non empty array, then that value [0] is non-empty.

2024-11-20 13:45 UTC, richardFocus reviewed
Updated as requested.

2024-11-20 13:45 UTC, richardFocus commented on Frontend/library/src/Config/SettingOption.ts
> +        const valueCodec = value.split(' ')[0];
Yes you are correct.

2024-11-20 13:57 UTC, richardFocus reviewed
Updated import path for Logger function

2024-11-20 13:59 UTC, richardFocus reviewed
Removed getStrackTrace()

2024-11-20 15:21 UTC, richardFocus reviewed
linting fix

2024-11-20 15:24 UTC, richardFocus reviewed
fixed linting

2024-11-22 05:52 UTC, closed without merging

2024-11-22 05:52 UTC, lukehb commented
Thanks for your contribution @richardFocus - I ended up having to change a bunch of stuff related to this because of some other work I was doing - you can see the landed result in: https://github.com/EpicGamesExt/PixelStreamingInfrastructure/pull/324