Added SDP for probator
EpicGames/PixelStreamingInfrastructure pull request #86
Opened 2024-04-23 02:15 UTC by zuvola

## Relevant components:
- [ ] Signalling server
- [x] Frontend library
- [ ] Frontend UI library
- [ ] Matchmaker
- [ ] Platform scripts
- [x] SFU

## Problem statement:
The current SFU does not always select the appropriate resolution stream even when simulcast is configured.
This may be because mediasoup is sending a stream for inspection under the name "probator", but it is not receiving this stream properly, so the inspection is not performed properly and the bitrate estimation is not done properly.

## Solution
Fixes #85 

![simul](https://github.com/EpicGamesExt/PixelStreamingInfrastructure/assets/1144427/9fcde09e-ca54-4def-887d-3dc203d5bf4f)

2024-05-03 01:10 UTC, lukehb commented
@zuvola Thanks for this digging any reference in mediasoup docs/discussion about this "probator"?

Also, when you remove this, does it fix the problem of not selecting the appropriate resolution stream?

2024-05-03 01:13 UTC, lukehb commented
Some further reading: https://mediasoup.discourse.group/t/probator-pli/3898/5

2024-05-07 00:55 UTC, zuvola commented
@lukehb 
Unfortunately I have not found any useful documentation.
The simulcast was working fine in the mediasoup demo at the following URL, and I found the probator when I was trying to find the difference.

https://v3demo.mediasoup.org/
https://github.com/versatica/mediasoup-demo

I just added the probator to the SDP using the mediasoup-client source as a reference and it works correctly, but I am not sure if this modification eliminates the root cause.
I am also not sure what happens when the probator packets are removed. Perhaps the bandwidth estimation will stop working.

2024-05-07 04:06 UTC, lukehb commented
With your PR applied, does automatic layer switching work when you restrict the bandwidth?

I do agree the probator does seem like a likely mechanism the mediasoup authors are using the probe for bitrate. 

> I am also not sure what happens when the probator packets are removed. Perhaps the bandwidth estimation will stop working.

I agree that bandwidth estimation will likely fail if probator is munged out. 

I think further investigation of the media soup demo is a good idea, perhaps we are configuring wrong.

2024-05-07 04:52 UTC, zuvola commented
By applying this PR, I have confirmed that it is working correctly, at least in my and my team member's environment.
It's a little hard to see, but I attached a working gif above.

2024-05-07 05:54 UTC, lukehb requested changes
Added a minor suggestion to give some context to future readers and maintainers of the code.

2024-05-07 05:54 UTC, lukehb commented on Frontend/library/src/VideoPlayer/StreamController.ts
> +
```suggestion
        // Do not add the track if the ID is `probator` as this is special track created by mediasoup for bitrate probing.
        // Refer to https://github.com/EpicGamesExt/PixelStreamingInfrastructure/pull/86 for more details.
```

2024-05-07 06:09 UTC, lukehb approved these changes
Had some discussions internally, this looks good to us. Thanks for finding this one and providing a neat and tidy PR. The Pixel Streaming user base and its maintainers thank you!

2024-05-07 06:14 UTC, lukehb commented
@mcottontensor To land and backport to 5.2, 5.3, 5.4 and make new releases.

2024-05-07 06:18 UTC, merged